server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /health {
        access_log off;
        default_type text/plain;
        return 200 'ok';
    }

    location = /index.html {
        add_header Cache-Control 'no-cache' always;
    }

    location ~* \.(js|css|ico|png|svg|woff2?)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
